### ISSUE TITLE
Create extension for revealing an example block on click/touch

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-extensions-lab#1]
Create an extension that initially hides example blocks with the role "result" and uses JavaScript to toggle the visibility of the content when a dedicated label (e.g., "View Result") is clicked or touched.

An example of this extension can be seen on the [AsciiDoc Syntax Quick Reference](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/) page on the Asciidoctor website. Another example can be found in the [Groovy documentation](http://beta.groovy-lang.org/docs/groovy-2.4.0-SNAPSHOT/html/documentation/core-semantics.html#static-type-checking).

**Comment by EdwinFLopez** [comment]
Hi all.
I see that this extension is merged. Nice!.
Is it possible to use it from asciidoctorj?
I have asciidoctorj installed by SDKMAN.
Thanks.
