### ISSUE TITLE
npm install mathoid error: Package libffi was not found in the pkg-config search path.

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/asciidoctor-extensions-lab#106]
Hello, I am getting an error while trying to npm install mathoid. I am on Mac OSX.

My initial error was this:
https://gist.github.com/siddjain/9502cd45ca56f7f19e03ad5897717527

To fix it I did brew install `brew install pkg-config`. The next iteration of npm install mathoid gave this:
https://gist.github.com/siddjain/be8a068331f9b187826342a00ef2f25f

To fix it I ran `brew install librsvg`. Now I get this while trying to do npm install mathoid:
https://gist.github.com/siddjain/0de020b16f9ffbba8a2196445922502f

it says:
```
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
```

but looks like I have libffi
```
$ brew instal libffi
Warning: libffi 3.2.1 is already installed and up-to-date
To reinstall 3.2.1, run `brew reinstall libffi`
```

further I can see:
```
$ ls /usr/local/opt/libffi/lib/pkgconfig
libffi.pc
```

I tried running `PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig npm install mathoid` but it gives same error

**Comment by mojavelinux** [comment]
I'll run through the installation process and see if I can figure out where things started to go wrong. I think the set up has fallout out of date and is need of some updates.

**Comment by mojavelinux** [comment]
I've decided to remove this extension from the lab.
