### ISSUE TITLE
Integrate asciidoc-coalescer.rb as extension/converter so as to make it available in the CLI

### ISSUE THREAD

**Issue by olib963** [asciidoctor/asciidoctor-extensions-lab#108]
There is a script (https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb) that you can use to merge your asciidoc files into one expanded asciidoc file. To me this is useful to create READMEs etc. for github while they cannot support features such as `include`. It would be nice if this could be integrated into the CLI

Original issue: https://github.com/asciidoctor/asciidoctor/issues/3374

**Comment by mojavelinux** [comment]
The asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
