### ISSUE TITLE
generate pdf with chart block

### ISSUE THREAD

**Issue by xu4wang** [asciidoctor/asciidoctor-extensions-lab#115]
I was trying to use the chart block extension.  the HTML file can be generated without any issue.

However, when I try
```
asciidoctor-pdf -r ./lib/chart-block-macro.rb sample.adoc
```

The generated pdf is without the chart.

I think this is not the correct way using asciidoctor-pdf,  I was not able to find document on generating pdf from a adoc file with chart block embedded. please give me some guide on this.

**Comment by mojavelinux** [comment]
That's correct. This extension is designed exclusively for the HTML backend. It relies on JavaScript libraries to create the charts and is thus not something that can be used with the PDF converter (at least not Asciioctor PDF). You might try https://github.com/mogztter/asciidoctor-pdf.js instead. It should work there.

**Comment by Mogztter** [comment]
Please note that this Ruby extension won't work as-is with asciidoctor-pdf.js but you can use https://github.com/mogztter/asciidoctor-chart which does almost the same thing but only supports the Chartist engine. 
I'm willing to add additional chart engines (C3, Chart.js,...) so if you want to contribute feel free to open an issue and/or a pull request 😉 

Here's roughly what you will need to do to get started:
```
$ npm init -y
$ npm i asciidoctor-pdf asciidoctor-chart --save
$ ./node_modules/.bin/asciidoctor-pdf -r asciidoctor-chart sample.adoc
```

You could also compile this Ruby extension to JavaScript using Opal but that would require a bit of work.

**Comment by mojavelinux** [comment]
> you can use mogztter/asciidoctor-chart 

Oh, that's right. We were supposed to remove this extension.

**Comment by xu4wang** [comment]
thanks @mojavelinux @Mogztter for clarification. For the time being, I work around this by saving as pdf via browser.

Will revisit this when I get more formatting requirement on the pdf.
