### ISSUE TITLE
adding row name to chart

### ISSUE THREAD

**Issue by xu4wang** [asciidoctor/asciidoctor-extensions-lab#117]
For the chart came with the demo 
```
chart::sample.csv[spline,500,400]
```
The generated chart is as below:
![image](https://user-images.githubusercontent.com/311397/80866167-e5302000-8cbf-11ea-84d4-71532a397eac.png)

The name for first row and second row are 0 and 1 by default, how should I change that to a more meaningful name?

BR,Austin

**Comment by Mogztter** [comment]
It's not possible but here's a proposal from @cdanger https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/114

**Comment by xu4wang** [comment]
> It's not possible but here's a proposal from @cdanger #114

thanks @Mogztter  I'm following #114 now.

**Comment by mojavelinux** [comment]
I believe this is now fixed in asciidoctor-chart. See https://github.com/asciidoctor/asciidoctor-chart
