### ISSUE TITLE
Add metadata object for tag message

### ISSUE THREAD

**Issue by liljenstolpe** [asciidoctor/asciidoctor-extensions-lab#120]
It might make more sense, if an annotated tag is associated with a commit, to use the annotation message rather than the commit message.  For example,

I just fixed a minor formatting issue, and that was all that was necessary to release the document as v1.0

Do I want my "commit message" to read "fixed font search path issue in prawn" or "document initial release"?

**Comment by liljenstolpe** [comment]
Pull request #119 resolves this.

**Comment by mojavelinux** [comment]
merged as 4273a0986f56e8d1f36d1db6b35ac5c5e26126c6. Thanks!
