### ISSUE TITLE
add link to the current script location as comment into the script

### ISSUE THREAD

**Issue by aisbergde** [asciidoctor/asciidoctor-extensions-lab#124]
if the link https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/scripts/asciidoc-coalescer.rb would be included in the comment section, or at least the repository link, it will be easier to find. And the source will be documented directly in the code.

**Comment by mojavelinux** [comment]
I intend to pull this out as a separate project, so I really don't want to mention it here. But that will really make it easy to find, and we can link to that. I'm hoping to get to it this week.

**Comment by aisbergde** [comment]
Separate project - sounds good!

Please keep us informed in any way, when this happens. I tested this script, and it did what it should do. I think, I can use it to prepare github wiki pages and readme files.

**Comment by mojavelinux** [comment]
I'll post back when it's ready. The new script I'm going to commit is far more accurate than this one.

**Comment by aisbergde** [comment]
@mojavelinux If you improve the script, maybe this feature could be included:

- convert not only one file, but allow converting also a folder containing asciidoc files recursively into a target folder

For example, I think about a folder structure containing wiki page definitions with includes, and it could be "exported" into a folder structure, ready to push to GitHub.

I know this could be done in the outer context when calling the script, but maybe it is not too complicated to do this directly in the script?

Maybe this could be combined with an option
- force the export folder to repeat the structure of the import folder (including delete existing documents, missing in the source)
- or only insert new and update existing but not to delete existing

**Comment by mojavelinux** [comment]
Please don't expand the scope of an issue. Once I have created the repository, I will post to it here. Then you can submit ideas to that repository using the issue tracker.

I can't promise that I can work on anything further. I'll be sharing the script so that others can benefit from the work I've already done. Other people may then come forward to improve on it.

**Comment by mojavelinux** [comment]
The asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
