### ISSUE TITLE
Graduate the asciidoc-coalescer.rb script to a separate project

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-extensions-lab#126]
There have been countless requests to make the functionality of the asciidoc-coalescer.rb script more readily available (which is reflected in the number of independent issues and discussion posts). Based on this interest and real world applicability, it's time to graduate the script to a separate project that can be installed as a RubyGem and either loaded as an extension or a converter (or both).

I've also developed major improvements to this script which I have yet to had time to share. When I set up the new project, I will incorporate those improvements into it. After that, any enhancements or bugs will be handled as separate issues in that project.

Related issues / requests:

* #108 
* #124 
* https://github.com/asciidoctor/asciidoctor.org/issues/159
* https://github.com/asciidoctor/asciidoctor/issues/3572
* https://github.com/asciidoctor/asciidoctor/issues/3312
* https://github.com/asciidoctor/asciidoctor/issues/1793
* https://github.com/asciidoctor/asciidoctor/issues/2378
* https://asciidoctor.zulipchat.com/#narrow/stream/279642-users/topic/AsciiDoc.20coalescer

**Comment by mojavelinux** [comment]
The only thing currently preventing me from creating the new project is to settle on a name. The project name for a library that performs an operation (as opposed to one that integrates with a technology) is typically a noun (e.g., namespace-doer or namespace-actionizer). Below is a list of candidates I'm considering. The challenge is figuring out what terminology to use for this functionality.

* asciidoctor-include-expander
* asciidoctor-uno
* asciidoctor-combiner
* asciidoctor-unifier
* asciidoctor-uninclude
* asciidoctor-one-asciidoc
* asciidoctor-inflater
* asciidoctor-expandizer

There's no doubt that asciidoctor-include-expander is the most self explanatory, but is also kind of boring. I'm fond of asciidoctor-uno because it was one of my favorite card games as a child and the goal of the game is to get down to a single card. Uno, of course, means one in several languages.

The other challenge is not to confuse the terminology with an operation that is done on the output (which is why I'm not suggesting out asciidoctor-bundler).

**Comment by windsurfer1122** [comment]
Just what came to me when reading your comments: `asciidoctor-merge-into-one`, `asciidoctor-single-source-creator`
Maybe this gives you some new ideas to find the final name.
Btw changing the repository name and script name afterwards should not be an issue for anyone.
Just my two cents

**Comment by mojavelinux** [comment]
We settled on the name asciidoctor-reducer.

**Comment by mojavelinux** [comment]
The asciidoc-coalescer.rb script has been redesigned and published as the [asciidoctor-reducer](https://github.com/asciidoctor/asciidoctor-reducer). It has also been released to RubyGems.org as a gem named **asciidoctor-reducer**. You can find installation instructions in the README for that project.
