### ISSUE TITLE
Create a proper README for the extensions lab

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-extensions-lab#44]
We need a README for this repository that covers (at least) the following information:

1. What extensions are available here
2. How to load an extension from the extension lab

We should also cover how these extensions are organized to help people create new ones.

This is a follow-up from the question posed in #35.

**Comment by mojavelinux** [comment]
@craigshoemaker pointed out that it would be helpful to understand how to transpile these extensions for use with Asciidoctor.js. Currently, that build material lives in Asciidoctor.js (see https://github.com/asciidoctor/asciidoctor.js/blob/master/Rakefile). We should be able to build extensions for Asciidoctor.js directly out of this repository....or we need to document what to do at the very least.

**Comment by edusantana** [comment]
I'm running a few extensions, and getting errors, I don't know if it's my fault or not.

Since this is a lab, it would be good to point where are **mature** the mature extensions.

**Comment by mojavelinux** [comment]
@edusantana At the moment there aren't a lot of mature extensions sets...unless you consider the top-level projects like asciidoctor-latex and asciidoctor-diagram. The plan is to graduate some of the extensions from the lab into named sets that can be loaded in Asciidoctor using a flag...but we haven't gotten there yet.

**Comment by mojavelinux** [comment]
We've covered everything in this issue, though we probably really need to have a short section on how to create a new extension. Let's handle the instructions for how to transpile an extension to Asciidoctor.js in a separate issue (maybe better handled in asciidoctor.js).

**Comment by mojavelinux** [comment]
I've added a section on how to create a new extension. I think we're ready to close. Any enhancements can be handled in a follow-up issue.
