### ISSUE TITLE
Rename registration files

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor-extensions-lab#46]
It would be more verbose to rename files inside `lib/*.rb` to include `registration` in their names:

```
lib/chart-block-macro-registration.rb
lib/chrome-inline-macro-registration.rb
lib/copyright-footer-postprocessor-registration.rb
lib/emoji-inline-macro-registration.rb
(...)
```

It would avoid errors like #45.

**Comment by mojavelinux** [comment]
I think this can be solved by the README. I'd rather not rename these files as this is not consistent with the Ruby way and the file names become too verbose.

In Ruby, the top-level name registers and activates the implementation files. That's how we've structured this repo. Once they are packaged in a gem (the long-term plan), the flag becomes `-r gist-block-macro`, which reads very nicely.
