### ISSUE TITLE
Class EmojiBlockMacro should be renamed to EmojiInlineMacro

### ISSUE THREAD

**Issue by edusantana** [asciidoctor/asciidoctor-extensions-lab#48]
I don't know if it matters, but in the file `emoji-inline-macro/extension.rb`, the class has a wrong name, it's `EmojiBlockMacro`, it should be `EmojiInlineMacro` instead.

**Comment by mojavelinux** [comment]
Indeed! We should definitely make that fix. Want to do the honor of sending the pull request?
