### ISSUE TITLE
Simple Tree Gen

### ISSUE THREAD

**Issue by sirinath** [asciidoctor/asciidoctor-extensions-lab#54]
I want to add simple tree diagrams to a text. Is possible to add an easy tree generation feature.

E.g.

```
- level 1 (A)
-- child of level A (B)
---  child of B
-- 2nd child of A
- 2nd child of root
```

**Comment by sirinath** [comment]
Better as part of: https://github.com/asciidoctor/asciidoctor-leanpub-converter/issues/46

**Comment by mojavelinux** [comment]
I'm pretty sure tree diagrams can be accomplished using Asciidoctor
Diagram. There's also an HTML-based solution in the extensions lab already
using the tree command. It depends on what exactly you're looking for.

**Comment by mojavelinux** [comment]
See https://twitter.com/mojavelinux/statuses/582567306284388352

**Comment by sirinath** [comment]
Thanks. This was what I was after. Can you rotate this and also make it into some other hierarchical diagram?

> Scalable file trees images w/ Asciidoctor Diagram!
```
[salt,format=svg]
----
{{T
+ src
++ main
+++ java
+++ test
}}
----
```

**Comment by mojavelinux** [comment]
I'm not sure. You'd need to look closer at the capabilities of salt. http://plantuml.sourceforge.net/salt.html
