### ISSUE TITLE
Multipage html5 converter breaks ToC support

### ISSUE THREAD

**Issue by eskatos** [asciidoctor/asciidoctor-extensions-lab#68]
With the help of #56 and by removing the hardcoded `noheader` attribute I tried to add ToCs in the chunked html files to no avail.

It looks like the `multipage-html5-converter` extension breaks `:toc:` handling somehow.

**Comment by eskatos** [comment]
Any insight on why and hints on where to look would be much appreciated.

**Comment by mojavelinux** [comment]
The multipage converter has be relocated to https://github.com/owenh000/asciidoctor-multipage. Please test using that converter. If the problem still exists, open an issue in that project.
