### ISSUE TITLE
Rendering dlists with multipage.rb 

### ISSUE THREAD

**Issue by arthur24b6** [asciidoctor/asciidoctor-extensions-lab#73]
I'm using the [multipage converter](https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/multipage-html5-converter.rb) to create chunked output. I ran into some issues trying to get the following markup to render properly: 
```
##### Example title

pipeline.<name>.example::

Example text
+
*Required.*
+
.Example
----
# pipeline configuration
pipeline.example.quorum = \
----
```
I'd only get the title of this in the output. I think this can be addressed by the reparenting function here: https://github.com/asciidoctor/asciidoctor-extensions-lab/blob/master/lib/multipage-html5-converter.rb#L60. I think it maybe sufficient to add something like:
```
      if block.context == :dlist
        block.parent = parent
      end
```
after the recursive call to reparent. Adding that I started getting the output that I expected. Not sure if this is the right approach.

**Comment by arthur24b6** [comment]
It also seems to be the case that any blocks on the dlist need to be reparented as well:
```
if block.context == :dlist
        block.parent = parent
        block.items.each do |i|
          if i[1].respond_to? 'parent'
            i[1].parent = parent
          end
        end
      end
```

**Comment by bsmith-n4** [comment]
Thanks @arthur24b6, this also works for me.

**Comment by mojavelinux** [comment]
The multipage converter has be relocated to https://github.com/owenh000/asciidoctor-multipage. Please test using that converter. If the problem still exists, open an issue in that project.
