### ISSUE TITLE
Create summaries from distributed definitions

### ISSUE THREAD

**Issue by ukubauka** [asciidoctor/asciidoctor-extensions-lab#93]
OK, couldn't find a better title... Here is what I want to do:
I am writing technical machine (not software :-) ) documentation using asciidoctor on atom. The machines are described by elements. With the element it is suitable to define the required maintenance work. Could be a small table, an admonition, ... whatever.

While for the writer it is suitable to have the maintenance described with the element, it is more suitable for the maintenance person to have a maintenance summary list at the end of the document.

I came up with tags and a self-including document, see code snippet below. Any better idea?

```
= Title

== Motor

Content not part of the maintenance tag

|===
| Element | Maintenance Instruction | Frequency

// tag::Maintenance[]
| icon:Maintenance[] <<Motor>> Oil | Change Motor Oil, use for salad | Daily
// end::Maintenance[]
|===

== Extruder

|===
| Element | Maintenance Instruction | Frequency

// tag::Maintenance[]
| icon:Maintenance[] <<Extruder>> Screw | Make nice & shiny | Before go to sleep
// end::Maintenance[]
|===


== Maintenance Summary

|===
| Element | Maintenance Instruction | Frequency

include::Source.adoc[tag=Maintenance]

|===

```

**Comment by mojavelinux** [comment]
If you are looking for help writing an extension, please ask in the project chat at https://chat.asciidoctor.org.
